add_newline = false
command_timeout = 2000

format = "$character$directory$git_branch$git_status"

[character]
format = "$symbol "
success_symbol = "[▲](bold white)"
error_symbol = "[▲](bold red)"

[directory]
truncate_to_repo = true
truncation_length = 0

[git_branch]
symbol = " "
truncation_length = 18
