# vim:fileencoding=utf-8:foldmethod=marker

font_family		JetBrainsMono NF
# bold_font		Hack Nerd Font Mono Bold 
# italic_font		Hack Nerd Font Mono Italic
# bold_italic_font 	Hack Nerd Font Mono Bold Italic
font_size 		14.0


disable_ligatures 	never

cursor 			#B62EB2
cursor_shape 		block
cursor_blink_interval 	0


enable_audio_bell 	no
allow_remote_control 	yes


hide_window_decorations 	titlebar-only
window_padding_width 		5
remember_window_size 		yes


mouse_hide_wait 3.0

editor /opt/homebrew/bin/nvim

scrollback_lines 10000

tab_bar_edge 		bottom
tab_bar_style 		powerline
tab_powerline_style 	slanted
tab_separator 		" | "
tab_activity_symbol 	"⚡️"
tab_bar_min_tabs 	1
tab_title_template 	{title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}



map cmd+t launch --type=tab --cwd=current

